# Initial configuration: use before requesting the first certificate.
server {
    listen 80;
    server_name 124.220.147.193;
    server_tokens off;

    location ^~ /.well-known/acme-challenge/ {
        root /var/lib/studyloop/acme;
        try_files $uri =404;
    }

    location / {
        return 308 https://124.220.147.193$request_uri;
    }
}
